### ISSUE TITLE
Past events are showing a server error

### ISSUE THREAD

**Issue by RCheesley** [mautic/Community-Portal#27]
I noticed today that **all** past events are throwing a server error when I was doing a demo video.

I thought initially maybe this was because the event had not been closed but I went to close the event and it still as throwing an error.

Here's the example:

https://community.mautic.org/assemblies/community-team/f/5/meetings/26

**Comment by froger** [comment]
Hello, 
Thanks for raising a support ticket as well, that was helpful for our internal-work ;)

We have fixed the issues, dues to a misconfiguration decidim->etherpad. The API_ETHERPAD_VERSION was wrong (`1.9.1` instead of `1`). 
Now the [https://community.mautic.org/assemblies/community-team/f/5/meetings/26](https://community.mautic.org/assemblies/community-team/f/5/meetings/26) display the pad in `read-only` mode correctly. 

![Screenshot 2023-10-11 at 11 43 59](https://github.com/mautic/Community-Portal/assets/3929108/9800d76a-9cb4-4590-9dde-5c20d242a9b9)


---

I've also check if this correction fixed by any luck the [related issue raised here: https://github.com/mautic/Community-Portal/issues/15](https://github.com/mautic/Community-Portal/issues/15). But it does not, and the routing fix we have to forbid pad creation needs to stay. 

Thanks

**Comment by RCheesley** [comment]
I think this will also close this issue: https://github.com/mautic/Community-Portal/issues/13 ?

**Comment by RCheesley** [comment]
Could the alternative option to having the pads domain offline be to implement [Auth0 login](https://github.com/ether/ep_openid_connect) (or maybe just admin only login for the Etherpad instance rather than preventing people accessing the instance directly? Just a thought if the 404 redirect/access protection is the culprit for this error.

**Comment by RCheesley** [comment]
The new events are now saving fine, so closing this one.
