### ISSUE TITLE
Reply-to email is set to change-me@example.org

### ISSUE THREAD

**Issue by RCheesley** [mautic/Community-Portal#28]
Hi folks,

A comment from one of our users is that the reply to email address that is used when messages are being sent out it's currently using:

`change-me@example.org`

 I can't see anywhere in the system settings where I can change this,  the documentation is not forthcoming either.  any suggestions where to start?

Ideally we would like this to be 

`hello@mautic.org`

**Comment by froger** [comment]
Hi Ruth, 
This has been fixed by changing environment values: 
![Screenshot 2023-10-11 at 11 49 59](https://github.com/mautic/Community-Portal/assets/3929108/a1eedca4-240b-4d0c-88e5-dac8b86936b5)

I have tested sending conversations, and the email is as expected: 
![Screenshot 2023-10-11 at 14 50 17](https://github.com/mautic/Community-Portal/assets/3929108/e9c7bbee-443b-4c80-8593-ef1362c82ee3)
